//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ProyectoFinalEntities : DbContext
    {
        public DB_ProyectoFinalEntities()
            : base("name=DB_ProyectoFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_Carros> TB_Carros { get; set; }
        public DbSet<TB_Clientes> TB_Clientes { get; set; }
        public DbSet<TB_Colores> TB_Colores { get; set; }
        public DbSet<TB_Compras> TB_Compras { get; set; }
        public DbSet<TB_Departamentos> TB_Departamentos { get; set; }
        public DbSet<TB_Empleados> TB_Empleados { get; set; }
        public DbSet<TB_Marcas> TB_Marcas { get; set; }
        public DbSet<TB_Paises> TB_Paises { get; set; }
        public DbSet<TB_Proveedores> TB_Proveedores { get; set; }
        public DbSet<TB_TipoCarros> TB_TipoCarros { get; set; }
        public DbSet<TB_TipoMotores> TB_TipoMotores { get; set; }
        public DbSet<TB_Usuarios> TB_Usuarios { get; set; }
        public DbSet<TB_Ventas> TB_Ventas { get; set; }
    }
}
