//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Carros
    {
        public TB_Carros()
        {
            this.TB_Ventas = new HashSet<TB_Ventas>();
        }
    
        public int Carro_ID { get; set; }
        public string Carro_Nombre { get; set; }
        public int Carro_Anio { get; set; }
        public int MarcaID_Carro { get; set; }
        public int TipoMID_Carro { get; set; }
        public int ProvID_Carro { get; set; }
        public int ColorID_Carro { get; set; }
        public int PaisID_Carro { get; set; }
    
        public virtual ICollection<TB_Ventas> TB_Ventas { get; set; }
        public virtual TB_Colores TB_Colores { get; set; }
        public virtual TB_Marcas TB_Marcas { get; set; }
        public virtual TB_Paises TB_Paises { get; set; }
        public virtual TB_Proveedores TB_Proveedores { get; set; }
        public virtual TB_TipoMotores TB_TipoMotores { get; set; }
    }
}
