//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Clientes
    {
        public TB_Clientes()
        {
            this.TB_Ventas = new HashSet<TB_Ventas>();
        }
    
        public int Cliente_ID { get; set; }
        public string Cliente_Nombre { get; set; }
        public string Cliente_Apellido { get; set; }
        public int Cliente_Tel { get; set; }
        public int Cliente_Nit { get; set; }
        public string Cliente_Email { get; set; }
    
        public virtual ICollection<TB_Ventas> TB_Ventas { get; set; }
    }
}
