//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Departamentos
    {
        public TB_Departamentos()
        {
            this.TB_Empleados = new HashSet<TB_Empleados>();
        }
    
        public int Depto_ID { get; set; }
        public string Depto_Nombre { get; set; }
    
        public virtual ICollection<TB_Empleados> TB_Empleados { get; set; }
    }
}
