//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Proveedores
    {
        public TB_Proveedores()
        {
            this.TB_Carros = new HashSet<TB_Carros>();
            this.TB_Compras = new HashSet<TB_Compras>();
        }
    
        public int Prov_ID { get; set; }
        public string Prov_Nombre { get; set; }
        public string Prov_Direccion { get; set; }
        public int Prov_Tel { get; set; }
        public string Prov_Email { get; set; }
    
        public virtual ICollection<TB_Carros> TB_Carros { get; set; }
        public virtual ICollection<TB_Compras> TB_Compras { get; set; }
    }
}
