//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Paises
    {
        public TB_Paises()
        {
            this.TB_Carros = new HashSet<TB_Carros>();
        }
    
        public int Pais_ID { get; set; }
        public string Pais_Nombre { get; set; }
    
        public virtual ICollection<TB_Carros> TB_Carros { get; set; }
    }
}
